### ISSUE TITLE
New error: failed to resolve location

### ISSUE THREAD

**Issue by Weicocu** [billykwooten/openweather-exporter#49]
This was working for me, but has stopped. It is giving the following error: 
time="2024-05-29T16:41:30Z" level=fatal msg="failed to resolve location:invalid character '<' looking for beginning of value"

I assume this has something to do with the location I'm putting in, but even switching to the example "Seattle, WA" gives this same error.

I did not change anything between when it was working and when it stopped working.

**Comment by billykwooten** [comment]
I have acknowledged this problem, I have created an issue [HERE](https://github.com/codingsince1985/geo-golang/issues/78) as it's related to the geo lookup library I use that uses openstreetmap.

I don't have time now, but I will dig into this and see if I can find/fix the problem in that library dependency.

**Comment by billykwooten** [comment]
I have figured out the problem, since we use nominatim to call out and get latitude and logitude. They have now changed their user policy for golang's http library. You must include a user-agent on the request.

I will be fixing this and removing external packages which will fix this, give me some time as it might be later today or tomorrow once I can sit down and code the fix.

**Comment by Weicocu** [comment]
No rush dude, your app is great and makes my life a little easier almost every day. Having it go down for a while was probably good to make me appreciate it more! 😁

**Comment by billykwooten** [comment]
Should be fixed @Weicocu with the new version I just pushed, let me know if you have any issues!

**Comment by Weicocu** [comment]
It's working perfectly again, thank you!!
